apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-frontend-deployment
  namespace: devboard
  labels:
    app: devboard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-frontend
  template:
    metadata:
      labels:
        app: devboard-frontend
    spec:
      containers:
      - name: devboard-frontend
        image: niteshmore15/devboard-frontend:be2d46819d30c8fd871e19e2dda9ef37a0b7ed35
        ports:
        - containerPort: 4173
        resources:
          requests: # min needed
            cpu: 10m
            memory: 64Mi
          limits: # max usable
            cpu: 250m
            memory: 128Mi


