```yaml
name: CD - Update Kubernetes Manifests

on:
  workflow_call:
    secrets:
      GITOPS_TOKEN:
        required: true

jobs:
  update-manifests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Kubernetes Repository
        uses: actions/checkout@v7
        with:
          repository: Nitesh150791/github-k8-project
          token: ${{ secrets.GITOPS_TOKEN }}
          ref: main
          path: github-k8-project

      - name: Verify Kubernetes Deployment Files
        working-directory: github-k8-project
        run: |
          echo "Files in k8s folder:"
          find k8s -maxdepth 2 -type f

          test -f k8s/backend-deployment.yml || {
            echo "ERROR: k8s/backend-deployment.yml not found"
            exit 1
          }

          test -f k8s/frontend-deployment.yml || {
            echo "ERROR: k8s/frontend-deployment.yml not found"
            exit 1
          }

      - name: Update Backend Image
        working-directory: github-k8-project
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        run: |
          sed -i \
            "s|image:.*devboard-backend.*|image: ${DOCKERHUB_USERNAME}/devboard-backend:${IMAGE_TAG}|" \
            k8s/backend-deployment.yml

      - name: Update Frontend Image
        working-directory: github-k8-project
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        run: |
          sed -i \
            "s|image:.*devboard-frontend.*|image: ${DOCKERHUB_USERNAME}/devboard-frontend:${IMAGE_TAG}|" \
            k8s/frontend-deployment.yml

      - name: Commit and Push Changes
        working-directory: github-k8-project
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "109646228+Nitesh150791@users.noreply.github.com"

          git add k8s/backend-deployment.yml \
                  k8s/frontend-deployment.yml

          if git diff --cached --quiet; then
            echo "No manifest changes to commit"
            exit 0
          fi

          git commit -m "Deploy ${IMAGE_TAG}"
          git pull --rebase origin main
          git push origin HEAD:main
```
