name: CD - GitOps

on:
  workflow_call:
    secrets:
      GITOPS_TOKEN:
        required: true

jobs:
  update-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v7
        with:
          repository: Nitesh150791/gitops-repo
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops-repo

      - name: Show GitOps repo files
        run: ls -la gitops-repo

      - name: Update Backend Image
        run: |
          sed -i "s|image:.*devboard-backend.*|image: ${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:${{ github.sha }}|" \
            gitops-repo/k8s/backend-deployment.yml

      - name: Update Frontend Image
        run: |
          sed -i "s|image:.*devboard-frontend.*|image: ${{ vars.DOCKERHUB_USERNAME }}/devboard-frontend:${{ github.sha }}|" \
            gitops-repo/k8s/frontend-deployment.yml

      - name: Commit GitOps Changes
        working-directory: gitops-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "109646228+Nitesh150791@users.noreply.github.com"
          git diff
          git add .
          git commit -m "Deploy ${{ github.sha }}" || echo "No changes to commit"
          git pull --rebase
          git push
